repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: ^jamesduxbury/
        types_or: [javascript, jsx, ts, tsx, json, css, markdown, yaml]
        additional_dependencies:
          - prettier@3.3.3

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: ^jamesduxbury/(public|node_modules|\.next)/
      - id: trailing-whitespace
        exclude: ^jamesduxbury/(public|node_modules|\.next)/
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=1024']
